[book]
authors = ["Alexiscomete"]
language = "fr"
multilingual = false
src = "src"
title = "Documentation du Skribi (Fr)"

[output.html]
additional-js = ["theme/skribi-highlight.js"]
additional-css = ["theme/skr-css.css"]
git-repository-url = "https://github.com/Dibi-programming-language/SkribiDocFr"
git-repository-icon = "fa-github"

[output.html.fold]
enable = true
level = 1

[output.html.search]
limit-results = 15

[output.html.code.hidelines]
skribi = "#"

[preprocessor.katex]
after = ["links"]
